import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import AuthProvider from "./AuthProvider";
import { Toaster } from "sonner";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export const viewport = {
//   width: '1024',
//   initialScale: 0,
// }

export default function RootLayout({ children}) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
      <Toaster position="top-center" richColors/>
      <AuthProvider>
      <StoreProvider>
        {children}
      </StoreProvider>
      </AuthProvider>
        </body>
    </html>
  );
}
